### PR TITLE
Fix codesigning issue on x86_64-apple-darwin

### LINKED ISSUE #5: Debug kill
This happens to me locally:
```julia
julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 8 × Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)

(grb) pkg> st
Status `/private/tmp/grb/Project.toml` (empty project)

(grb) pkg> add https://github.com/jump-dev/Gurobi_jll.jl
     Cloning git-repo `https://github.com/jump-dev/Gurobi_jll.jl`
    Updating git-repo `https://github.com/jump-dev/Gurobi_jll.jl`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  Downloaded artifact: Gurobi
  Downloaded artifact: Gurobi
    Updating `/private/tmp/grb/Project.toml`
  [c018c7e6] + Gurobi_jll v11.0.1 `https://github.com/jump-dev/Gurobi_jll.jl#master`
    Updating `/private/tmp/grb/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.5.0
  [21216c6a] + Preferences v1.4.3
  [c018c7e6] + Gurobi_jll v11.0.1 `https://github.com/jump-dev/Gurobi_jll.jl#master`
  [56f22d72] + Artifacts
  [ade2ca70] + Dates
  [8f399da3] + Libdl
  [de0858da] + Printf
  [fa267f1f] + TOML v1.0.3
  [4ec0a83e] + Unicode
Precompiling project...
  1 dependency successfully precompiled in 2 seconds. 2 already precompiled.

julia> using Gurobi_jll
zsh: killed     julia --project=grb
```

I assume because of something that I have locally?

### PR DESCRIPTION
**Pull request by odow**
Closes #5

### CODE REVIEW

**Comment by simonbowly** [comment]
@odow does this indicate a problem with the signing of the Gurobi library, or is it a more general julia/mac issue?

**Comment by odow** [comment]
I have no idea. I guess not (because I can use the `gurobi_cl` binary). It happens to other binaries:

image

What do you see as the output of ```run(`codesign -dvv $(Gurobi_jll.libgurobi)`)``` on an M-series Mac?

**Comment by simonbowly** [comment]
v10 appears with an adhoc signature and v11 with no signature, which seems odd. A normal Gurobi install has a proper signature on the library, but it's also a macos universal build while the conda packages only contain one architecture. I'll check if we can improve something. Thanks for resolving it here.

**Comment by odow** [comment]
It might also be that the way we download it and unpack through Julia's Tar.jl... not sure. At minimum, we can work around the issue, and now I know what to look for in future.

**Comment by odow** [comment]
I can load Gurobi 10 without any issues (this version doesn't have the `--remove-signature` in it), so maybe something has changed on your end:
```julia
(grb) pkg> add Gurobi_jll@10
   Resolving package versions...
   Installed Gurobi_jll ─ v10.0.3
     Failure artifact: Gurobi
  Downloaded artifact: Gurobi
    Updating `/private/tmp/grb/Project.toml`
⌃ [c018c7e6] ↓ Gurobi_jll v11.0.1 ⇒ v10.0.3
    Updating `/private/tmp/grb/Manifest.toml`
⌃ [c018c7e6] ↓ Gurobi_jll v11.0.1 ⇒ v10.0.3
        Info Packages marked with ⌃ have new versions available and may be upgradable.
Precompiling project...
  1 dependency successfully precompiled in 2 seconds. 2 already precompiled.

julia> using Gurobi_jll

julia> Gurobi_jll.libgurobi
"/Users/oscar/.julia/artifacts/9747c6ef8280f98316f91aea9accc9e5808d92ed/lib/libgurobi100.dylib"

julia> run(`codesign -dvv $(Gurobi_jll.libgurobi)`)
/Users/oscar/.julia/artifacts/9747c6ef8280f98316f91aea9accc9e5808d92ed/lib/libgurobi100.dylib: code object is not signed at all
```

**Pull request merged**
